kind: ConfigMap
apiVersion: v1
metadata:
  name: observability-metrics-custom-allowlist
  namespace: open-cluster-management-observability
data:
  metrics_list.yaml: |
    names:
      - node_memory_Active_bytes # this custom metric is being collected from your managed clusters
      - rest_client_requests_total- # this default metric is not being collected from your managed clusters
