#!/usr/bin/env bash

clusterClaim=ssli

if [ $# -ge 1 ]
then
    clusterClaim=$1
fi

kubeConf=~/kubeconf/$clusterClaim-kubeconfig

unset KUBECONFIG
echo y | oc login --insecure-skip-tls-verify --token="$OCP_SA_TOKEN" --server=https://api.collective.aws.red-chesterfield.com:6443 1>&2 > /dev/null

if ! oc get clusterclaim.hive "$clusterClaim" >/dev/null 2>&1; then
    echo "create a new clusterclaim $clusterClaim"
    cat <<EOF | oc apply -f -
apiVersion: hive.openshift.io/v1
kind: ClusterClaim
metadata:
 name: $clusterClaim
 namespace: demo
 labels:
   do-not-delete: "true"
 annotations:
   cluster.open-cluster-management.io/createmanagedcluster: "false"
spec:
 clusterPoolName: demo-aws-495
 subjects:
 - apiGroup: rbac.authorization.k8s.io
   kind: Group
   name: demo
 - kind: ServiceAccount
   name: demo
   namespace: demo
EOF
  sleep 5
fi

# export cluster KUBECONFIG
clusterDeploymentNS=$(oc get clusterclaim.hive -n demo $clusterClaim -o jsonpath='{.spec.namespace}')
kubeconfigSecret=$(oc get clusterdeployment -n "$clusterDeploymentNS" -o jsonpath='{.items[].spec.clusterMetadata.adminKubeconfigSecretRef.name}')
oc get secret "$kubeconfigSecret" -n "$clusterDeploymentNS" -o 'go-template={{index .data "kubeconfig"}}' | base64 --decode > $kubeConf
export KUBECONFIG=$kubeConf
echo "run 'export KUBECONFIG=$kubeConf' to access your cluster"
