#!/usr/bin/env bash

clusterClaim=ssli

if [ $# -ge 1 ]
then
    clusterClaim=$1
fi

unset KUBECONFIG
echo y | oc login --token="$OCP_SA_TOKEN" --server=https://api.collective.aws.red-chesterfield.com:6443 1>&2 > /dev/null
oc delete clusterclaim.hive "$clusterClaim"
